# Generated by Django 4.0.2 on 2022-03-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_los_nodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='nombre',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
