# Generated by Django 4.0.2 on 2022-03-03 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_los_nodos', '0002_extend_nodo_nombre_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='port',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid port format', regex='^([0-9]/){1,2}[0-9]+')]),
        ),
    ]
