# Generated by Django 4.0.2 on 2022-03-09 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_los_nodos', '0003_alter_nodo_port_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='port',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Invalid port format', regex='^([0-9]/){1,2}[0-9]+')]),
        ),
        migrations.AlterUniqueTogether(
            name='nodo',
            unique_together={('switch', 'port')},
        ),
    ]
