# Generated by Django 4.0.2 on 2022-03-04 22:01

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    for model in ('Switch', 'Equipo', 'AP'):
        Model = apps.get_model('todos_los_nodos', model)
        new_ct = ContentType.objects.get_for_model(Model)
        Model.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('todos_los_nodos', '0004_alter_nodo_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='ipdevice',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_%(app_label)s.%(class)s_set+',
                                    to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
