# Generated by Django 4.0.2 on 2022-03-07 16:42

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    IPDevice = apps.get_model("todos_los_nodos", "IPDevice")
    Status = apps.get_model("monitoreo", "status")
    for device in IPDevice.objects.filter(ip__isnull=False):
        try:
            matching_status = Status.objects.get(ipDevice=device)
            device.alive = matching_status.alive
            device.lastAlive = matching_status.lastAlive
            device.save()
        except Status.DoesNotExist:
            pass  # not in watchlist, keep default


class Migration(migrations.Migration):

    dependencies = [
        ('todos_los_nodos', '0005_ipdevice_polymorphic'),
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdevice',
            name='alive',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='ipdevice',
            name='lastAlive',
            field=models.DateTimeField(editable=False, null=True),
        ),
        # Add existing status
        migrations.RunPython(
            code=forwards_func,
            reverse_code=migrations.RunPython.noop,
        )
    ]
