# Generated by Django 4.0.2 on 2022-03-14 22:33

import django.core.validators
from django.db import migrations, models
import todos_los_nodos.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todos_los_nodos', '0006_ipdevice_alive_lastalive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='mac',
            field=todos_los_nodos.fields.MacField(unique=True, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='nodo',
            name='port',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Invalid port format', regex='^([0-9]+/){1,2}[0-9]+')]),
        ),
    ]
