# Generated by Django 4.0.3 on 2022-03-25 22:58

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # Migrate existing extensions
    Telefonos = apps.get_model('todos_los_nodos', 'Telefono')
    for telefono in Telefonos.objects.all():
        if usuario := telefono.usuario:
            usuario.ext = telefono.ext
            usuario.save()


def backwards_func(apps, schema_editor):
    # Migrate extensions back
    Usuario = apps.get_model('todos_los_nodos', 'Usuario')
    for usuario in Usuario.objects.all():
        if telefono := usuario.telefono_set.get():
            telefono.ext = usuario.ext
            telefono.save()


class Migration(migrations.Migration):
    dependencies = [
        ('todos_los_nodos', '0007_alter_nodo_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ext',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.RunPython(
            code=forwards_func,
            reverse_code=backwards_func,
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='ext',
        ),
    ]
