# Generated by Django 4.0.3 on 2022-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_los_nodos', '0008_move_ext_from_telefono_to_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdevice',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
    ]
