# Generated by Django 4.0.3 on 2022-04-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_los_nodos', '0009_alter_ipdevice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.RenameField(
            model_name='nodo',
            old_name='notas',
            new_name='description',
        ),
        migrations.AddField(
            model_name='nodo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salas'), (2, 'CDC'), (3, 'Usuario'), (4, 'Otro')], default=4),
        ),
    ]
