# Generated by Django 4.0.3 on 2022-08-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos_los_nodos', '0010_alter_nodo_notas_nodo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='mac',
        ),
    ]
