# Generated by Django 4.0.3 on 2022-03-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todos_los_nodos', '0008_move_ext_from_telefono_to_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cowork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('nodes', models.ManyToManyField(to='todos_los_nodos.nodo', verbose_name='nodo')),
                ('users', models.ManyToManyField(to='todos_los_nodos.usuario', verbose_name='usuario')),
            ],
        ),
    ]
