# Generated by Django 4.0.2 on 2022-02-28 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todos_los_nodos', '0001_initial'),
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=False)),
                ('lastAlive', models.DateTimeField(null=True)),
                ('ipDevice', models.ForeignKey(limit_choices_to=models.Q(('ip__isnull', False)), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='todos_los_nodos.ipdevice', verbose_name='device')),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('recurrence', models.DurationField()),
                ('active', models.BooleanField(default=False)),
                ('devices', models.ManyToManyField(through='monitoreo.Status', to='todos_los_nodos.IPDevice')),
                ('schedule', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.schedule')),
                ('subscribers', models.ManyToManyField(to='monitoreo.Subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.watchlist'),
        ),
    ]
